default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trailblazers_development

test:
  <<: *default
  database: trailblazers_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  database: trailblazers_production
  username: trailblazers
  password: <%= ENV['TRAILBLAZERS_DATABASE_PASSWORD'] %>
